### ISSUE TITLE
Which Architecture?

### ISSUE THREAD

**Issue by illmaren** [peschmae/exporter-go-mystrom#3]
Hi,
would be nice to know which architecture is supported for this exporter.

Using a Raspberry Pi 4b as internet monitoring server and wanted to add 1-2 mystrom switches...

**Comment by peschmae** [comment]
I've updated the README, to list the tested & supported architectures.

Right now I only had a raspberry pi running on 32bit raspian available to test, so I couldn't confirm it for arm64 yet, but since it's a rather simple script and GOs cross compatibility is well tested, I'm confident it should also work if you have a 64bit raspian installation

**Comment by illmaren** [comment]
Its not working with the 64bit raspian.
Image requests amd64 but the raspian (atleast mine) runs on arm64/v8

**Comment by peschmae** [comment]
Can you try the arm64 binary available at https://github.com/peschmae/exporter-go-mystrom/releases/tag/1.1.1 ?

I´ve just setup the automatic build using github actions, and there is now also a arm64 binary

**Comment by peschmae** [comment]
If you use containers, you can now use the image available on the github registry: https://github.com/peschmae/exporter-go-mystrom/pkgs/container/exporter-go-mystrom

This is a multiplatform image, that should work for arm64 as well

**Comment by illmaren** [comment]
Ok thanks the last one actually worked. The auto created files from github didnt work that well too.
